# AI School - Epoch 1 - Iteration 4

## Learning Objectives

By the end of this session, you will be able to:
- Create and manipulate Pandas DataFrames and Series
- Load data from various file formats (CSV, Excel, JSON)
- Navigate DataFrames using different indexing methods
- Identify and handle missing data
- Clean messy datasets through filtering, transforming, and removing duplicates
- Perform basic exploratory data inspection

## 01. Introduction to Pandas

###  What is Pandas?
- Overview: Data manipulation library built on NumPy
- Primary data structures: Series and DataFrame
- Why Pandas? Real-world use cases

### Installation and Setup

1- **Use python virtual environments when working with libraries**
```
$ python3 -m venv omc_venv
$ source omc_venv/bin/activate
$ pip install pandas 
```

2- **All python libraries are installed using the `pip install` command**

In [171]:
import pandas as pd
import numpy as np

# Check version
print(pd.__version__)

3.0.1

---

## 02. Series: The Building Block

### a. Creating Series

In [172]:
# From list
s = pd.Series([10, 20, 30, 40])
s

0    10
1    20
2    30
3    40
dtype: int64

In [173]:
# From dictionary
s = pd.Series({'a': 10, 'b': 20, 'c': 30})
s

a    10
b    20
c    30
dtype: int64

In [175]:
# With custom index
s = pd.Series([10, 20, 30], index=['x', 'y', 'z'])
s

x    10
y    20
z    30
dtype: int64

In [176]:
# From NumPy array
s = pd.Series(np.array([1, 2, 3, 4, 5]))
s

0    1
1    2
2    3
3    4
4    5
dtype: int64

### b. Series Attributes

- `s.values` - underlying NumPy array
- `s.index` - index labels
- `s.dtype` - data type
- `s.shape` - dimensions
- `s.size` - number of elements

In [178]:
s = pd.Series([10, 20, 30, 40, 50], index=['a', 'b', 'c', 'd', 'e'])

In [179]:
print("Series:")
print(s)
print()

print(f"s.values → {s.values}")
print(f"s.index  → {s.index.tolist()}")
print(f"s.dtype  → {s.dtype}")
print(f"s.shape  → {s.shape}")
print(f"s.size   → {s.size}")

Series:
a    10
b    20
c    30
d    40
e    50
dtype: int64

s.values → [10 20 30 40 50]
s.index  → ['a', 'b', 'c', 'd', 'e']
s.dtype  → int64
s.shape  → (5,)
s.size   → 5

### c. Series Operations

- Indexing: `s[0]`, `s['label']`
- Slicing: `s[1:3]`, `s['a':'c']`
- Boolean indexing: `s[s > 20]`
- Basic statistics: `s.mean()`, `s.sum()`, `s.max()`

In [ ]:
print("Series:")
print(s)
print()

print(f"s.iloc[0]        → {s.iloc[0]}")
print(f"s['c']      → {s['c']}")
print()

print(f"s.iloc[1:3]      → {s.iloc[1:3].tolist()}")
print(f"s['a':'c']  → {s['a':'c'].tolist()}")
print()

print(f"s[s > 20]   → {s[s > 20].tolist()}")
print()

print(f"s.mean()    → {s.mean()}")
print(f"s.sum()     → {s.sum()}")
print(f"s.max()     → {s.max()}")

Series:
a    10
b    20
c    30
d    40
e    50
dtype: int64

s[0]        → 10
s['c']      → 30

s[1:3]      → [20, 30]
s['a':'c']  → [10, 20, 30]

s[s > 20]   → [30, 40, 50]

s.mean()    → 30.0
s.sum()     → 150
s.max()     → 50

---

## 03. DataFrames

### a. Creating DataFrames

#### - From dictionary:

In [181]:
data = {
    'name': ['Alice', 'Bob', 'Charlie', 'David'],
    'age': [25, 30, 35, 28],
    'city': ['NYC', 'LA', 'Chicago', 'Boston']
}
df = pd.DataFrame(data)
df

      name  age     city
0    Alice   25      NYC
1      Bob   30       LA
2  Charlie   35  Chicago
3    David   28   Boston

#### - From list of dictionaries:

In [182]:
data = [
    {'name': 'Alice', 'age': 25},
    {'name': 'Bob', 'age': 30}
]
df = pd.DataFrame(data)
df

    name  age
0  Alice   25
1    Bob   30

#### - From NumPy array:

In [183]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
df = pd.DataFrame(arr, columns=['A', 'B', 'C'])
df

   A  B  C
0  1  2  3
1  4  5  6

### b. DataFrame Anatomy
- Rows and columns
- Index (row labels)
- Column names
- Data types per column

### c. Essential DataFrame Attributes

In [184]:
df = pd.DataFrame({
    'name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
    'age': [25, 30, 35, 28, 32],
    'city': ['NYC', 'LA', 'Chicago', 'Boston', 'NYC'],
    'salary': [70000, 80000, 90000, 75000, 85000]
})

print("DataFrame:")
df

DataFrame:

      name  age     city  salary
0    Alice   25      NYC   70000
1      Bob   30       LA   80000
2  Charlie   35  Chicago   90000
3    David   28   Boston   75000
4      Eve   32      NYC   85000

In [186]:
print(f"df.shape    → {df.shape}")
print(f"df.columns  → {df.columns.tolist()}")
print(f"df.index    → {df.index.tolist()}")

df.shape    → (5, 4)
df.columns  → ['name', 'age', 'city', 'salary']
df.index    → [0, 1, 2, 3, 4]

In [187]:
print("df.dtypes:")
print(df.dtypes)

df.dtypes:
name        str
age       int64
city        str
salary    int64
dtype: object

In [123]:
print("df.info():")
df.info()

df.info():
<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    5 non-null      str
 1   age     5 non-null      int64
 2   city    5 non-null      str
 3   salary  5 non-null      int64
dtypes: int64(2), str(2)
memory usage: 292.0 bytes

In [188]:
print("df.head():")
print(df.head(2))

df.head():
    name  age city  salary
0  Alice   25  NYC   70000
1    Bob   30   LA   80000

In [125]:
print("df.tail(2):")
print(df.tail(2))

df.tail(2):
    name  age    city  salary
3  David   28  Boston   75000
4    Eve   32     NYC   85000

In [126]:
print("df.describe():")
print(df.describe())

df.describe():
             age       salary
count   5.000000      5.00000
mean   30.000000  80000.00000
std     3.807887   7905.69415
min    25.000000  70000.00000
25%    28.000000  75000.00000
50%    30.000000  80000.00000
75%    32.000000  85000.00000
max    35.000000  90000.00000

## 04. Data Loading

### a. Reading CSV Files

In [190]:
# Basic read
df = pd.read_csv('sales_data.csv')
df.head()

,order_id,customer_name,product,quantity,price,order_date,city,payment_method
0,1001,Alice Johnson,Laptop,1,899.99,2024-01-15,New York,Credit Card
1,1002,Bob Smith,Mouse,2,25.50,2024-01-16,Los Angeles,PayPal
2,1003,Charlie Brown,Keyboard,1,79.99,2024-01-16,Chicago,Credit Card
3,1004,Diana Prince,Monitor,1,299.99,2024-01-17,?,Debit Card
4,1005,Eve Davis,Laptop,1,899.99,2024-01-18,Boston,Credit Card

In [192]:
# Common parameters
sales_df = pd.read_csv('sales_data.csv',
                 sep=',',              # delimiter
                 header=0,             # row number for column names
                 index_col=0,          # column to use as index
                 na_values=['NA', '?'] # additional NA values
                )
sales_df.head(10)

,customer_name,product,quantity,price,order_date,city,payment_method
order_id,,,,,,,
1001,Alice Johnson,Laptop,1,899.99,2024-01-15,New York,Credit Card
1002,Bob Smith,Mouse,2,25.50,2024-01-16,Los Angeles,PayPal
1003,Charlie Brown,Keyboard,1,79.99,2024-01-16,Chicago,Credit Card
1004,Diana Prince,Monitor,1,299.99,2024-01-17,NaN,Debit Card
1005,Eve Davis,Laptop,1,899.99,2024-01-18,Boston,Credit Card
1006,Frank Miller,Mouse,3,25.50,2024-01-18,New York,NaN
1007,Grace Lee,Headphones,2,149.99,2024-01-19,Seattle,PayPal
1008,Henry Wilson,Keyboard,1,79.99,NaN,Miami,Credit Card
1009,Ivy Chen,Webcam,1,89.99,2024-01-20,Austin,Debit Card
1010,Bob Smith,Mouse,2,25.50,2024-01-16,Los Angeles,PayPal

### b. Reading Other Formats

```python
# Excel
df = pd.read_excel('data.xlsx', sheet_name='Sheet1')
Reading Other Formats
# JSON
df = pd.read_json('data.json')

# From URL
url = 'https://example.com/data.csv'
df = pd.read_csv(url)
```

In [194]:
# First look
sales_df.head()
sales_df.info()
sales_df.describe()

<class 'pandas.DataFrame'>
RangeIndex: 15 entries, 1001 to 1015
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   customer_name   15 non-null     str
 1   product         14 non-null     str
 2   quantity        15 non-null     int64
 3   price           14 non-null     float64
 4   order_date      14 non-null     str
 5   city            14 non-null     str
 6   payment_method  13 non-null     str
dtypes: float64(1), int64(1), str(5)
memory usage: 972.0 bytes

        quantity      price
count  15.000000   14.00000
mean    1.666667  285.85000
std     1.112697  345.51855
min     1.000000   25.50000
25%     1.000000   39.12250
50%     1.000000  119.99000
75%     2.000000  299.99000
max     5.000000  899.99000

---

## 05. Indexing and Selection

### a. Selecting Columns

In [195]:
sales_df.head()

,customer_name,product,quantity,price,order_date,city,payment_method
order_id,,,,,,,
1001,Alice Johnson,Laptop,1,899.99,2024-01-15,New York,Credit Card
1002,Bob Smith,Mouse,2,25.50,2024-01-16,Los Angeles,PayPal
1003,Charlie Brown,Keyboard,1,79.99,2024-01-16,Chicago,Credit Card
1004,Diana Prince,Monitor,1,299.99,2024-01-17,NaN,Debit Card
1005,Eve Davis,Laptop,1,899.99,2024-01-18,Boston,Credit Card

In [198]:
# Single column (returns Series)
sales_df['product']

order_id
1001        Laptop
1002         Mouse
1003      Keyboard
1004       Monitor
1005        Laptop
1006         Mouse
1007    Headphones
1008      Keyboard
1009        Webcam
1010         Mouse
1011        Laptop
1012           NaN
1013       Monitor
1014         Mouse
1015        Laptop
Name: product, dtype: str

In [199]:
# Multiple columns (returns DataFrame)
sales_df[['product', 'price']]

             product   price
order_id
1001          Laptop  899.99
1002           Mouse   25.50
1003        Keyboard   79.99
1004         Monitor  299.99
1005          Laptop  899.99
1006           Mouse   25.50
1007      Headphones  149.99
1008        Keyboard   79.99
1009          Webcam   89.99
1010           Mouse   25.50
1011          Laptop  899.99
1012             NaN  199.99
1013         Monitor  299.99
1014           Mouse   25.50
1015          Laptop     NaN

### b. Selecting Rows by Position: `.iloc[]`

In [ ]:
# Single row
sales_df.iloc[0]

array(['Alice Johnson', 'Laptop', np.int64(1), np.float64(899.99),
       '2024-01-15', 'New York', 'Credit Card'], dtype=object)

In [203]:
# Multiple rows
sales_df.iloc[0:3]         # slicing
sales_df.iloc[[0, 2, 4]]   # multiple indices

,customer_name,product,quantity,price,order_date,city,payment_method
order_id,,,,,,,
1001,Alice Johnson,Laptop,1,899.99,2024-01-15,New York,Credit Card
1003,Charlie Brown,Keyboard,1,79.99,2024-01-16,Chicago,Credit Card
1005,Eve Davis,Laptop,1,899.99,2024-01-18,Boston,Credit Card

In [205]:
# Rows and columns
sales_df.iloc[0:3, 1:3]    
sales_df.iloc[:, 0]

order_id
1001      Alice Johnson
1002          Bob Smith
1003      Charlie Brown
1004       Diana Prince
1005          Eve Davis
1006       Frank Miller
1007          Grace Lee
1008       Henry Wilson
1009           Ivy Chen
1010          Bob Smith
1011         Kate Brown
1012        Liam Taylor
1013         Mia Garcia
1014      Noah Martinez
1015    Olivia Anderson
Name: customer_name, dtype: str

### c. Selecting Rows by Label: `.loc[]`

In [207]:
# By index label
sales_df.loc[1001]            # row with index label order_id=1001
sales_df.loc[1001:1004]          # inclusive slicing!

,customer_name,product,quantity,price,order_date,city,payment_method
order_id,,,,,,,
1001,Alice Johnson,Laptop,1,899.99,2024-01-15,New York,Credit Card
1002,Bob Smith,Mouse,2,25.50,2024-01-16,Los Angeles,PayPal
1003,Charlie Brown,Keyboard,1,79.99,2024-01-16,Chicago,Credit Card
1004,Diana Prince,Monitor,1,299.99,2024-01-17,NaN,Debit Card

In [ ]:
# By condition
sales_df.loc[sales_df['quantity'] > 3]

,customer_name,product,quantity,price,order_date,city,payment_method
order_id,,,,,,,
1014,Noah Martinez,Mouse,5,25.5,2024-01-23,Dallas,Credit Card

In [210]:
# Rows and columns by label
sales_df.loc[1001:1005, 'product':'city']
# sales_df.loc[:, 'city']

           product  quantity   price  order_date         city
order_id
1001        Laptop         1  899.99  2024-01-15     New York
1002         Mouse         2   25.50  2024-01-16  Los Angeles
1003      Keyboard         1   79.99  2024-01-16      Chicago
1004       Monitor         1  299.99  2024-01-17          NaN
1005        Laptop         1  899.99  2024-01-18       Boston

### d. Boolean Indexing (Filtering)

In [211]:
# Single condition
sales_df[sales_df['price'] > 25]

,customer_name,product,quantity,price,order_date,city,payment_method
order_id,,,,,,,
1001,Alice Johnson,Laptop,1,899.99,2024-01-15,New York,Credit Card
1002,Bob Smith,Mouse,2,25.50,2024-01-16,Los Angeles,PayPal
1003,Charlie Brown,Keyboard,1,79.99,2024-01-16,Chicago,Credit Card
1004,Diana Prince,Monitor,1,299.99,2024-01-17,NaN,Debit Card
1005,Eve Davis,Laptop,1,899.99,2024-01-18,Boston,Credit Card
1006,Frank Miller,Mouse,3,25.50,2024-01-18,New York,NaN
1007,Grace Lee,Headphones,2,149.99,2024-01-19,Seattle,PayPal
1008,Henry Wilson,Keyboard,1,79.99,NaN,Miami,Credit Card
1009,Ivy Chen,Webcam,1,89.99,2024-01-20,Austin,Debit Card
1010,Bob Smith,Mouse,2,25.50,2024-01-16,Los Angeles,PayPal
1011,Kate Brown,Laptop,1,899.99,2024-01-21,Denver,Credit Card
1012,Liam Taylor,NaN,1,199.99,2024-01-21,Portland,PayPal
1013,Mia Garcia,Monitor,2,299.99,2024-01-22,Phoenix,NaN
1014,Noah Martinez,Mouse,5,25.50,2024-01-23,Dallas,Credit Card

In [212]:
# Multiple conditions (use ~, & and | with parentheses!)
sales_df[(sales_df['quantity'] > 1) & (sales_df['price'] < 100)]
sales_df[(sales_df['quantity'] == 1) | (sales_df['price'] > 500)]

,customer_name,product,quantity,price,order_date,city,payment_method
order_id,,,,,,,
1001,Alice Johnson,Laptop,1,899.99,2024-01-15,New York,Credit Card
1003,Charlie Brown,Keyboard,1,79.99,2024-01-16,Chicago,Credit Card
1004,Diana Prince,Monitor,1,299.99,2024-01-17,NaN,Debit Card
1005,Eve Davis,Laptop,1,899.99,2024-01-18,Boston,Credit Card
1008,Henry Wilson,Keyboard,1,79.99,NaN,Miami,Credit Card
1009,Ivy Chen,Webcam,1,89.99,2024-01-20,Austin,Debit Card
1011,Kate Brown,Laptop,1,899.99,2024-01-21,Denver,Credit Card
1012,Liam Taylor,NaN,1,199.99,2024-01-21,Portland,PayPal
1015,Olivia Anderson,Laptop,1,NaN,2024-01-23,San Diego,Debit Card

In [ ]:
# Using .isin()
sales_df[sales_df['city'].isin(['New York', 'Los Angeles', 'Chicago'])]

,customer_name,product,quantity,price,order_date,city,payment_method
order_id,,,,,,,
1001,Alice Johnson,Laptop,1,899.99,2024-01-15,New York,Credit Card
1004,Diana Prince,Monitor,1,299.99,2024-01-17,NaN,Debit Card
1005,Eve Davis,Laptop,1,899.99,2024-01-18,Boston,Credit Card
1011,Kate Brown,Laptop,1,899.99,2024-01-21,Denver,Credit Card
1013,Mia Garcia,Monitor,2,299.99,2024-01-22,Phoenix,NaN
1015,Olivia Anderson,Laptop,1,NaN,2024-01-23,San Diego,Debit Card

In [215]:
# Using .str methods
sales_df[sales_df['customer_name'].str.startswith('B')]
sales_df[sales_df['customer_name'].str.contains('son', na=False)]
sales_df[sales_df['product'].str.contains('top', case=False, na=False)]

,customer_name,product,quantity,price,order_date,city,payment_method
order_id,,,,,,,
1001,Alice Johnson,Laptop,1,899.99,2024-01-15,New York,Credit Card
1005,Eve Davis,Laptop,1,899.99,2024-01-18,Boston,Credit Card
1011,Kate Brown,Laptop,1,899.99,2024-01-21,Denver,Credit Card
1015,Olivia Anderson,Laptop,1,NaN,2024-01-23,San Diego,Debit Card

---

## 06. Data Cleaning Essentials

### a. Handling Missing Data

**Detecting Missing Values:**

In [216]:
sales_df.isnull()          # Boolean DataFrame

,customer_name,product,quantity,price,order_date,city,payment_method
order_id,,,,,,,
1001,False,False,False,False,False,False,False
1002,False,False,False,False,False,False,False
1003,False,False,False,False,False,False,False
1004,False,False,False,False,False,True,False
1005,False,False,False,False,False,False,False
1006,False,False,False,False,False,False,True
1007,False,False,False,False,False,False,False
1008,False,False,False,False,True,False,False
1009,False,False,False,False,False,False,False
1010,False,False,False,False,False,False,False
1011,False,False,False,False,False,False,False
1012,False,True,False,False,False,False,False
1013,False,False,False,False,False,False,True
1014,False,False,False,False,False,False,False
1015,False,False,False,True,False,False,False

In [217]:
sales_df.isnull().sum()    # Count per column

customer_name     0
product           1
quantity          0
price             1
order_date        1
city              1
payment_method    2
dtype: int64

In [218]:
sales_df.isnull().any()    # Boolean per column

customer_name     False
product            True
quantity          False
price              True
order_date         True
city               True
payment_method     True
dtype: bool

In [145]:
# Alternative
sales_df.isna()            # same as isnull()

,customer_name,product,quantity,price,order_date,city,payment_method
order_id,,,,,,,
1001,False,False,False,False,False,False,False
1002,False,False,False,False,False,False,False
1003,False,False,False,False,False,False,False
1004,False,False,False,False,False,True,False
1005,False,False,False,False,False,False,False
1006,False,False,False,False,False,False,True
1007,False,False,False,False,False,False,False
1008,False,False,False,False,True,False,False
1009,False,False,False,False,False,False,False
1010,False,False,False,False,False,False,False
1011,False,False,False,False,False,False,False
1012,False,True,False,False,False,False,False
1013,False,False,False,False,False,False,True
1014,False,False,False,False,False,False,False
1015,False,False,False,True,False,False,False

**Removing Missing Values:**

In [146]:
# Drop rows with any missing values
df_clean = sales_df.dropna()

In [147]:
# Drop rows where specific column is missing
df_clean = sales_df.dropna(subset=['city'])

In [148]:
# Drop columns with any missing values
df_clean = sales_df.dropna(axis=1)

In [149]:
# Drop rows only if ALL values are missing
df_clean = sales_df.dropna(how='all')

# Drop rows if more than n non-NA values are missing
df_clean = sales_df.dropna(thresh=3)

**Filling Missing Values:**

In [ ]:
# Fill with a specific value
sales_df['price'].fillna(0)
sales_df.fillna(0)  # all columns

# Fill with column mean/median
sales_df['price'].fillna(sales_df['price'].mean())
sales_df['price'].fillna(sales_df['price'].median())

# Forward fill (use previous value)
sales_df['price'].ffill()

# Backward fill (use next value)
sales_df['price'].bfill()

# Fill different columns differently
sales_df.fillna({'price': 0, 'city': 'Unknown', 'payment_method': 'Not Specified'})

,customer_name,product,quantity,price,order_date,city,payment_method
order_id,,,,,,,
1001,Alice Johnson,Laptop,1,899.99,2024-01-15,New York,Credit Card
1002,Bob Smith,Mouse,2,25.50,2024-01-16,Los Angeles,PayPal
1003,Charlie Brown,Keyboard,1,79.99,2024-01-16,Chicago,Credit Card
1004,Diana Prince,Monitor,1,299.99,2024-01-17,Unknown,Debit Card
1005,Eve Davis,Laptop,1,899.99,2024-01-18,Boston,Credit Card
1006,Frank Miller,Mouse,3,25.50,2024-01-18,New York,Not Specified
1007,Grace Lee,Headphones,2,149.99,2024-01-19,Seattle,PayPal
1008,Henry Wilson,Keyboard,1,79.99,NaN,Miami,Credit Card
1009,Ivy Chen,Webcam,1,89.99,2024-01-20,Austin,Debit Card
1010,Bob Smith,Mouse,2,25.50,2024-01-16,Los Angeles,PayPal
1011,Kate Brown,Laptop,1,899.99,2024-01-21,Denver,Credit Card
1012,Liam Taylor,NaN,1,199.99,2024-01-21,Portland,PayPal
1013,Mia Garcia,Monitor,2,299.99,2024-01-22,Phoenix,Not Specified
1014,Noah Martinez,Mouse,5,25.50,2024-01-23,Dallas,Credit Card
1015,Olivia Anderson,Laptop,1,0.00,2024-01-23,San Diego,Debit Card

### b. Removing Duplicates

In [222]:
# Check for duplicates
sales_df.duplicated()           # Boolean Series
sales_df.duplicated().sum()     # Count

np.int64(1)

In [223]:
# View duplicate rows
sales_df[sales_df.duplicated()]

,customer_name,product,quantity,price,order_date,city,payment_method
order_id,,,,,,,
1010,Bob Smith,Mouse,2,25.5,2024-01-16,Los Angeles,PayPal

In [224]:
# Keep last occurrence instead of first
df_clean = sales_df.drop_duplicates()
df_clean

,customer_name,product,quantity,price,order_date,city,payment_method
order_id,,,,,,,
1001,Alice Johnson,Laptop,1,899.99,2024-01-15,New York,Credit Card
1002,Bob Smith,Mouse,2,25.50,2024-01-16,Los Angeles,PayPal
1003,Charlie Brown,Keyboard,1,79.99,2024-01-16,Chicago,Credit Card
1004,Diana Prince,Monitor,1,299.99,2024-01-17,NaN,Debit Card
1005,Eve Davis,Laptop,1,899.99,2024-01-18,Boston,Credit Card
1006,Frank Miller,Mouse,3,25.50,2024-01-18,New York,NaN
1007,Grace Lee,Headphones,2,149.99,2024-01-19,Seattle,PayPal
1008,Henry Wilson,Keyboard,1,79.99,NaN,Miami,Credit Card
1009,Ivy Chen,Webcam,1,89.99,2024-01-20,Austin,Debit Card
1011,Kate Brown,Laptop,1,899.99,2024-01-21,Denver,Credit Card
1012,Liam Taylor,NaN,1,199.99,2024-01-21,Portland,PayPal
1013,Mia Garcia,Monitor,2,299.99,2024-01-22,Phoenix,NaN
1014,Noah Martinez,Mouse,5,25.50,2024-01-23,Dallas,Credit Card
1015,Olivia Anderson,Laptop,1,NaN,2024-01-23,San Diego,Debit Card

In [154]:
# Based on specific columns
df_clean = sales_df.drop_duplicates(subset=['product', 'customer_name'])

### c. Data Type Conversions

In [225]:
data = {
    'id': [1001, 1002, 1003, 1004, 1005],
    'age': [25.0, 30.0, 35.0, 28.0, 32.0],  # stored as float, should be int
    'score': ['85.5', '90.0', '78.3', '92.1', '88.7'],  # stored as string, should be float
    'price': ['99.99', '149.50', '79.00', '120.25', '199.99'],  # stored as string, should be float
    'date': ['2024-01-15', '2024-01-16', '2024-01-17', '2024-01-18', '2024-01-19']  # stored as string, should be datetime
}

df = pd.DataFrame(data)

In [226]:
df.dtypes

id         int64
age      float64
score        str
price        str
date         str
dtype: object

In [227]:
df['age'] = df['age'].astype(int)
df['price'] = df['price'].astype(float)
df['date'] = pd.to_datetime(df['date'])
df = df.astype({'score': float, 'id': str})

In [228]:
df.dtypes

id                  str
age               int64
score           float64
price           float64
date     datetime64[us]
dtype: object

### d. Renaming Columns

In [230]:
df.rename(columns={'price': 'prix'}, inplace=True)
df

     id  age  score    prix       date
0  1001   25   85.5   99.99 2024-01-15
1  1002   30   90.0  149.50 2024-01-16
2  1003   35   78.3   79.00 2024-01-17
3  1004   28   92.1  120.25 2024-01-18
4  1005   32   88.7  199.99 2024-01-19

```python
# Rename all columns (must provide all names)
df.columns = ['new_col1', 'new_col2', 'new_col3']
```

## 07. Basic Exploratory Inspection

### a. Value Counts

In [162]:
# Frequency of unique values
sales_df['city'].value_counts()

city
New York       2
Los Angeles    2
Chicago        1
Boston         1
Seattle        1
Miami          1
Austin         1
Denver         1
Portland       1
Phoenix        1
Dallas         1
San Diego      1
Name: count, dtype: int64

In [231]:
# As proportions
sales_df['city'].value_counts(normalize=True)*100

city
New York       14.285714
Los Angeles    14.285714
Chicago         7.142857
Boston          7.142857
Seattle         7.142857
Miami           7.142857
Austin          7.142857
Denver          7.142857
Portland        7.142857
Phoenix         7.142857
Dallas          7.142857
San Diego       7.142857
Name: proportion, dtype: float64

### b. Unique Values

In [233]:
# Number of unique values
sales_df['product'].nunique()

6

In [165]:
# List unique values
sales_df['product'].unique()

<StringArray>
['Laptop', 'Mouse', 'Keyboard', 'Monitor', 'Headphones', 'Webcam', nan]
Length: 7, dtype: str

## 08. Saving Data

In [166]:
# Save to CSV
df.to_csv('data.csv', index=False)